from datetime import date, datetime
from typing import Optional

from sqlalchemy import BigInteger, Boolean, Date, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.orm import Base


class Profile(Base):
    __tablename__ = "profiles"

    symbol: Mapped[str] = mapped_column(String(10), primary_key=True)
    company_name: Mapped[Optional[str]] = mapped_column(String(255))
    currency: Mapped[Optional[str]] = mapped_column(String(10))
    cik: Mapped[Optional[str]] = mapped_column(String(20))
    isin: Mapped[Optional[str]] = mapped_column(String(20))
    cusip: Mapped[Optional[str]] = mapped_column(String(20))
    exchange_full_name: Mapped[Optional[str]] = mapped_column(String(100), index=True)
    sector: Mapped[Optional[str]] = mapped_column(String(100), index=True)
    industry: Mapped[Optional[str]] = mapped_column(String(100))
    website: Mapped[Optional[str]] = mapped_column(String(255))
    description: Mapped[Optional[str]] = mapped_column(Text)
    ceo: Mapped[Optional[str]] = mapped_column(String(255))
    country: Mapped[Optional[str]] = mapped_column(String(10))
    ipo_date: Mapped[Optional[date]] = mapped_column(Date)
    full_time_employees: Mapped[Optional[int]] = mapped_column(Integer)
    phone: Mapped[Optional[str]] = mapped_column(String(30))
    address: Mapped[Optional[str]] = mapped_column(String(255))
    city: Mapped[Optional[str]] = mapped_column(String(100))
    state: Mapped[Optional[str]] = mapped_column(String(50))
    zip: Mapped[Optional[str]] = mapped_column(String(20))
    image: Mapped[Optional[str]] = mapped_column(String(255))
    last_dividend: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    beta: Mapped[Optional[float]] = mapped_column(Numeric(6, 3))
    is_etf: Mapped[Optional[bool]] = mapped_column(Boolean)
    is_fund: Mapped[Optional[bool]] = mapped_column(Boolean)
    is_adr: Mapped[Optional[bool]] = mapped_column(Boolean)
    is_actively_trading: Mapped[Optional[bool]] = mapped_column(Boolean)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    quote: Mapped[Optional["Quote"]] = relationship(
        back_populates="profile", uselist=False, cascade="all, delete-orphan"
    )


class Quote(Base):
    __tablename__ = "quotes"

    symbol: Mapped[str] = mapped_column(
        String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True
    )
    exchange: Mapped[Optional[str]] = mapped_column(String(20))
    price: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    change: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    change_percentage: Mapped[Optional[float]] = mapped_column(Numeric(8, 4))
    volume: Mapped[Optional[int]] = mapped_column(BigInteger)
    average_volume: Mapped[Optional[int]] = mapped_column(BigInteger)
    day_low: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    day_high: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    year_low: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    year_high: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    market_cap: Mapped[Optional[int]] = mapped_column(BigInteger)
    price_avg_50: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    price_avg_200: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    open: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    previous_close: Mapped[Optional[float]] = mapped_column(Numeric(12, 4))
    quote_timestamp: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    profile: Mapped["Profile"] = relationship(back_populates="quote")


class IncomeStatement(Base):
    __tablename__ = "income_statements"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    reported_currency: Mapped[str] = mapped_column(String(10))
    cik: Mapped[str] = mapped_column(String(20))
    filing_date: Mapped[date] = mapped_column(Date)
    accepted_date: Mapped[datetime] = mapped_column(DateTime)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    revenue: Mapped[int] = mapped_column(BigInteger)
    cost_of_revenue: Mapped[int] = mapped_column(BigInteger)
    gross_profit: Mapped[int] = mapped_column(BigInteger)
    research_and_development_expenses: Mapped[int] = mapped_column(BigInteger)
    general_and_administrative_expenses: Mapped[int] = mapped_column(BigInteger)
    selling_and_marketing_expenses: Mapped[int] = mapped_column(BigInteger)
    selling_general_and_admin_expenses: Mapped[int] = mapped_column(BigInteger)
    other_expenses: Mapped[int] = mapped_column(BigInteger)
    operating_expenses: Mapped[int] = mapped_column(BigInteger)
    cost_and_expenses: Mapped[int] = mapped_column(BigInteger)
    net_interest_income: Mapped[int] = mapped_column(BigInteger)
    interest_income: Mapped[int] = mapped_column(BigInteger)
    interest_expense: Mapped[int] = mapped_column(BigInteger)
    depreciation_and_amortization: Mapped[int] = mapped_column(BigInteger)
    ebitda: Mapped[int] = mapped_column(BigInteger)
    ebit: Mapped[int] = mapped_column(BigInteger)
    non_operating_income_excl_interest: Mapped[int] = mapped_column(BigInteger)
    operating_income: Mapped[int] = mapped_column(BigInteger)
    total_other_income_expenses_net: Mapped[int] = mapped_column(BigInteger)
    income_before_tax: Mapped[int] = mapped_column(BigInteger)
    income_tax_expense: Mapped[int] = mapped_column(BigInteger)
    net_income_from_continuing_ops: Mapped[int] = mapped_column(BigInteger)
    net_income_from_discontinued_ops: Mapped[int] = mapped_column(BigInteger)
    other_adjustments_to_net_income: Mapped[int] = mapped_column(BigInteger)
    net_income: Mapped[int] = mapped_column(BigInteger)
    net_income_deductions: Mapped[int] = mapped_column(BigInteger)
    bottom_line_net_income: Mapped[int] = mapped_column(BigInteger)
    eps: Mapped[float] = mapped_column(Numeric(10, 4))
    eps_diluted: Mapped[float] = mapped_column(Numeric(10, 4))
    weighted_avg_shs_out: Mapped[int] = mapped_column(BigInteger)
    weighted_avg_shs_out_dil: Mapped[int] = mapped_column(BigInteger)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class BalanceSheet(Base):
    __tablename__ = "balance_sheets"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    reported_currency: Mapped[str] = mapped_column(String(10))
    cik: Mapped[str] = mapped_column(String(20))
    filing_date: Mapped[date] = mapped_column(Date)
    accepted_date: Mapped[datetime] = mapped_column(DateTime)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    cash_and_cash_equivalents: Mapped[int] = mapped_column(BigInteger)
    short_term_investments: Mapped[int] = mapped_column(BigInteger)
    cash_and_short_term_investments: Mapped[int] = mapped_column(BigInteger)
    net_receivables: Mapped[int] = mapped_column(BigInteger)
    accounts_receivables: Mapped[int] = mapped_column(BigInteger)
    other_receivables: Mapped[int] = mapped_column(BigInteger)
    inventory: Mapped[int] = mapped_column(BigInteger)
    prepaids: Mapped[int] = mapped_column(BigInteger)
    other_current_assets: Mapped[int] = mapped_column(BigInteger)
    total_current_assets: Mapped[int] = mapped_column(BigInteger)
    property_plant_equipment_net: Mapped[int] = mapped_column(BigInteger)
    goodwill: Mapped[int] = mapped_column(BigInteger)
    intangible_assets: Mapped[int] = mapped_column(BigInteger)
    goodwill_and_intangible_assets: Mapped[int] = mapped_column(BigInteger)
    long_term_investments: Mapped[int] = mapped_column(BigInteger)
    tax_assets: Mapped[int] = mapped_column(BigInteger)
    other_non_current_assets: Mapped[int] = mapped_column(BigInteger)
    total_non_current_assets: Mapped[int] = mapped_column(BigInteger)
    other_assets: Mapped[int] = mapped_column(BigInteger)
    total_assets: Mapped[int] = mapped_column(BigInteger)
    total_payables: Mapped[int] = mapped_column(BigInteger)
    account_payables: Mapped[int] = mapped_column(BigInteger)
    other_payables: Mapped[int] = mapped_column(BigInteger)
    accrued_expenses: Mapped[int] = mapped_column(BigInteger)
    short_term_debt: Mapped[int] = mapped_column(BigInteger)
    capital_lease_obligations_current: Mapped[int] = mapped_column(BigInteger)
    tax_payables: Mapped[int] = mapped_column(BigInteger)
    deferred_revenue: Mapped[int] = mapped_column(BigInteger)
    other_current_liabilities: Mapped[int] = mapped_column(BigInteger)
    total_current_liabilities: Mapped[int] = mapped_column(BigInteger)
    long_term_debt: Mapped[int] = mapped_column(BigInteger)
    capital_lease_obligations_noncurrent: Mapped[int] = mapped_column(BigInteger)
    deferred_revenue_non_current: Mapped[int] = mapped_column(BigInteger)
    deferred_tax_liabilities_non_current: Mapped[int] = mapped_column(BigInteger)
    other_non_current_liabilities: Mapped[int] = mapped_column(BigInteger)
    total_non_current_liabilities: Mapped[int] = mapped_column(BigInteger)
    other_liabilities: Mapped[int] = mapped_column(BigInteger)
    capital_lease_obligations: Mapped[int] = mapped_column(BigInteger)
    total_liabilities: Mapped[int] = mapped_column(BigInteger)
    treasury_stock: Mapped[int] = mapped_column(BigInteger)
    preferred_stock: Mapped[int] = mapped_column(BigInteger)
    common_stock: Mapped[int] = mapped_column(BigInteger)
    retained_earnings: Mapped[int] = mapped_column(BigInteger)
    additional_paid_in_capital: Mapped[int] = mapped_column(BigInteger)
    accumulated_other_comprehensive_inc: Mapped[int] = mapped_column(BigInteger)
    other_total_stockholders_equity: Mapped[int] = mapped_column(BigInteger)
    total_stockholders_equity: Mapped[int] = mapped_column(BigInteger)
    total_equity: Mapped[int] = mapped_column(BigInteger)
    minority_interest: Mapped[int] = mapped_column(BigInteger)
    total_liabilities_and_equity: Mapped[int] = mapped_column(BigInteger)
    total_investments: Mapped[int] = mapped_column(BigInteger)
    total_debt: Mapped[int] = mapped_column(BigInteger)
    net_debt: Mapped[int] = mapped_column(BigInteger)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CashFlowStatement(Base):
    __tablename__ = "cash_flow_statements"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    reported_currency: Mapped[str] = mapped_column(String(10))
    cik: Mapped[str] = mapped_column(String(20))
    filing_date: Mapped[date] = mapped_column(Date)
    accepted_date: Mapped[datetime] = mapped_column(DateTime)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    net_income: Mapped[int] = mapped_column(BigInteger)
    depreciation_and_amortization: Mapped[int] = mapped_column(BigInteger)
    deferred_income_tax: Mapped[int] = mapped_column(BigInteger)
    stock_based_compensation: Mapped[int] = mapped_column(BigInteger)
    change_in_working_capital: Mapped[int] = mapped_column(BigInteger)
    accounts_receivables: Mapped[int] = mapped_column(BigInteger)
    inventory: Mapped[int] = mapped_column(BigInteger)
    accounts_payables: Mapped[int] = mapped_column(BigInteger)
    other_working_capital: Mapped[int] = mapped_column(BigInteger)
    other_non_cash_items: Mapped[int] = mapped_column(BigInteger)
    net_cash_from_operating_activities: Mapped[int] = mapped_column(BigInteger)
    investments_in_ppe: Mapped[int] = mapped_column(BigInteger)
    acquisitions_net: Mapped[int] = mapped_column(BigInteger)
    purchases_of_investments: Mapped[int] = mapped_column(BigInteger)
    sales_maturities_of_investments: Mapped[int] = mapped_column(BigInteger)
    other_investing_activities: Mapped[int] = mapped_column(BigInteger)
    net_cash_from_investing_activities: Mapped[int] = mapped_column(BigInteger)
    net_debt_issuance: Mapped[int] = mapped_column(BigInteger)
    long_term_net_debt_issuance: Mapped[int] = mapped_column(BigInteger)
    short_term_net_debt_issuance: Mapped[int] = mapped_column(BigInteger)
    net_stock_issuance: Mapped[int] = mapped_column(BigInteger)
    net_common_stock_issuance: Mapped[int] = mapped_column(BigInteger)
    common_stock_issuance: Mapped[int] = mapped_column(BigInteger)
    common_stock_repurchased: Mapped[int] = mapped_column(BigInteger)
    net_preferred_stock_issuance: Mapped[int] = mapped_column(BigInteger)
    net_dividends_paid: Mapped[int] = mapped_column(BigInteger)
    common_dividends_paid: Mapped[int] = mapped_column(BigInteger)
    preferred_dividends_paid: Mapped[int] = mapped_column(BigInteger)
    other_financing_activities: Mapped[int] = mapped_column(BigInteger)
    net_cash_from_financing_activities: Mapped[int] = mapped_column(BigInteger)
    effect_of_forex_changes_on_cash: Mapped[int] = mapped_column(BigInteger)
    net_change_in_cash: Mapped[int] = mapped_column(BigInteger)
    cash_at_end_of_period: Mapped[int] = mapped_column(BigInteger)
    cash_at_beginning_of_period: Mapped[int] = mapped_column(BigInteger)
    operating_cash_flow: Mapped[int] = mapped_column(BigInteger)
    capital_expenditure: Mapped[int] = mapped_column(BigInteger)
    free_cash_flow: Mapped[int] = mapped_column(BigInteger)
    income_taxes_paid: Mapped[int] = mapped_column(BigInteger)
    interest_paid: Mapped[int] = mapped_column(BigInteger)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class KeyMetrics(Base):
    __tablename__ = "key_metrics"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    reported_currency: Mapped[str] = mapped_column(String(10))
    market_cap: Mapped[int] = mapped_column(BigInteger)
    enterprise_value: Mapped[int] = mapped_column(BigInteger)
    ev_to_sales: Mapped[float] = mapped_column(Numeric(12, 6))
    ev_to_operating_cash_flow: Mapped[float] = mapped_column(Numeric(12, 6))
    ev_to_free_cash_flow: Mapped[float] = mapped_column(Numeric(12, 6))
    ev_to_ebitda: Mapped[float] = mapped_column(Numeric(12, 6))
    net_debt_to_ebitda: Mapped[float] = mapped_column(Numeric(12, 6))
    current_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    income_quality: Mapped[float] = mapped_column(Numeric(12, 6))
    graham_number: Mapped[float] = mapped_column(Numeric(12, 6))
    graham_net_net: Mapped[float] = mapped_column(Numeric(18, 6))
    tax_burden: Mapped[float] = mapped_column(Numeric(12, 6))
    interest_burden: Mapped[float] = mapped_column(Numeric(12, 6))
    working_capital: Mapped[int] = mapped_column(BigInteger)
    invested_capital: Mapped[int] = mapped_column(BigInteger)
    return_on_assets: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_return_on_assets: Mapped[float] = mapped_column(Numeric(12, 6))
    return_on_tangible_assets: Mapped[float] = mapped_column(Numeric(12, 6))
    return_on_equity: Mapped[float] = mapped_column(Numeric(12, 6))
    return_on_invested_capital: Mapped[float] = mapped_column(Numeric(12, 6))
    return_on_capital_employed: Mapped[float] = mapped_column(Numeric(12, 6))
    earnings_yield: Mapped[float] = mapped_column(Numeric(12, 6))
    free_cash_flow_yield: Mapped[float] = mapped_column(Numeric(12, 6))
    capex_to_operating_cash_flow: Mapped[float] = mapped_column(Numeric(12, 6))
    capex_to_depreciation: Mapped[float] = mapped_column(Numeric(12, 6))
    capex_to_revenue: Mapped[float] = mapped_column(Numeric(12, 6))
    sga_to_revenue: Mapped[float] = mapped_column(Numeric(12, 6))
    rd_to_revenue: Mapped[float] = mapped_column(Numeric(12, 6))
    stock_based_comp_to_revenue: Mapped[float] = mapped_column(Numeric(12, 6))
    intangibles_to_total_assets: Mapped[float] = mapped_column(Numeric(12, 6))
    average_receivables: Mapped[int] = mapped_column(BigInteger)
    average_payables: Mapped[int] = mapped_column(BigInteger)
    average_inventory: Mapped[int] = mapped_column(BigInteger)
    days_of_sales_outstanding: Mapped[float] = mapped_column(Numeric(12, 6))
    days_of_payables_outstanding: Mapped[float] = mapped_column(Numeric(12, 6))
    days_of_inventory_outstanding: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cycle: Mapped[float] = mapped_column(Numeric(12, 6))
    cash_conversion_cycle: Mapped[float] = mapped_column(Numeric(12, 6))
    free_cash_flow_to_equity: Mapped[int] = mapped_column(BigInteger)
    free_cash_flow_to_firm: Mapped[float] = mapped_column(Numeric(20, 4))
    tangible_asset_value: Mapped[int] = mapped_column(BigInteger)
    net_current_asset_value: Mapped[int] = mapped_column(BigInteger)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Ratios(Base):
    __tablename__ = "ratios"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    reported_currency: Mapped[str] = mapped_column(String(10))
    gross_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    ebit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    ebitda_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    pretax_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    continuous_operations_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    net_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    bottom_line_profit_margin: Mapped[float] = mapped_column(Numeric(12, 6))
    receivables_turnover: Mapped[float] = mapped_column(Numeric(12, 6))
    payables_turnover: Mapped[float] = mapped_column(Numeric(12, 6))
    inventory_turnover: Mapped[float] = mapped_column(Numeric(12, 6))
    fixed_asset_turnover: Mapped[float] = mapped_column(Numeric(12, 6))
    asset_turnover: Mapped[float] = mapped_column(Numeric(12, 6))
    current_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    quick_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    solvency_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    cash_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_earnings_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_earnings_growth_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    forward_price_to_earnings_growth_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_book_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_sales_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_free_cash_flow_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_operating_cash_flow_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_to_assets_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_to_equity_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_to_capital_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    long_term_debt_to_capital_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    financial_leverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    working_capital_turnover_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cash_flow_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cash_flow_sales_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    free_cash_flow_operating_cf_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_service_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    interest_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    short_term_operating_cf_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cash_flow_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    capital_expenditure_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    dividend_paid_and_capex_coverage_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    dividend_payout_ratio: Mapped[float] = mapped_column(Numeric(12, 6))
    dividend_yield: Mapped[float] = mapped_column(Numeric(12, 6))
    dividend_yield_percentage: Mapped[float] = mapped_column(Numeric(12, 6))
    revenue_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    net_income_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    interest_debt_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    cash_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    book_value_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    tangible_book_value_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    shareholders_equity_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cash_flow_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    capex_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    free_cash_flow_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    net_income_per_ebt: Mapped[float] = mapped_column(Numeric(12, 6))
    ebt_per_ebit: Mapped[float] = mapped_column(Numeric(12, 6))
    price_to_fair_value: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_to_market_cap: Mapped[float] = mapped_column(Numeric(12, 6))
    effective_tax_rate: Mapped[float] = mapped_column(Numeric(12, 6))
    enterprise_value_multiple: Mapped[float] = mapped_column(Numeric(12, 6))
    dividend_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class FinancialGrowth(Base):
    __tablename__ = "financial_growth"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date)
    fiscal_year: Mapped[str] = mapped_column(String(4), primary_key=True)
    period: Mapped[str] = mapped_column(String(10), primary_key=True)
    reported_currency: Mapped[str] = mapped_column(String(10))
    revenue_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    gross_profit_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    ebit_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_income_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    net_income_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    eps_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    eps_diluted_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    weighted_avg_shares_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    weighted_avg_shares_diluted_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    dividends_per_share_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    operating_cash_flow_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    receivables_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    inventory_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    asset_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    book_value_per_share_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    debt_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    rd_expense_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    sga_expenses_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    free_cash_flow_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_revenue_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_revenue_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_revenue_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_operating_cf_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_operating_cf_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_operating_cf_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_shareholders_equity_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_shareholders_equity_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_shareholders_equity_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_dividend_per_share_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_dividend_per_share_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_dividend_per_share_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    ebitda_growth: Mapped[float] = mapped_column(Numeric(12, 6))
    growth_capital_expenditure: Mapped[float] = mapped_column(Numeric(12, 6))
    ten_y_bottom_line_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    five_y_bottom_line_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    three_y_bottom_line_net_income_growth_per_share: Mapped[float] = mapped_column(Numeric(12, 6))
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class EnterpriseValue(Base):
    __tablename__ = "enterprise_values"

    symbol: Mapped[str] = mapped_column(String(10), ForeignKey("profiles.symbol", ondelete="CASCADE"), primary_key=True)
    date: Mapped[date] = mapped_column(Date, primary_key=True)
    stock_price: Mapped[float] = mapped_column(Numeric(12, 4))
    number_of_shares: Mapped[int] = mapped_column(BigInteger)
    market_capitalization: Mapped[int] = mapped_column(BigInteger)
    minus_cash_and_equivalents: Mapped[int] = mapped_column(BigInteger)
    add_total_debt: Mapped[int] = mapped_column(BigInteger)
    enterprise_value: Mapped[int] = mapped_column(BigInteger)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
